[package]
name = "mj-dns-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
hickory-server = { version = "0.24.1", features = ["tokio-rustls"] }
async-trait = "0.1.77"
trust-dns-resolver = "0.20.4"
serde = "1.0.202"
toml = "0.8.13"